version: '3.8'


services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8008:8000"
    environment:
      - DATABASE_URL= postgresql+psycopg2://dev:111@db:5432/dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/14/main
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=111
      - POSTGRES_DB=dev
    container_name: db
  minio:
    restart: always
    image: minio/minio
    command: server /data --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    environment:
      ACCESS_KEY: minioadmin123
      SECRET_KEY: minioadmin123
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ~/minio/data:/data

volumes:
  postgres_data:
  data:
